### ISSUE TITLE
Inquiries about translated file locations

### ISSUE THREAD

**Issue by marload** [anyscale/academy#1]
Hello, Anyscale.
Ray is a popular library in Korea, too. So I will contribute by translating Korean users so that they can easily study through this tutorial. Where should I put the translated notebook file?

Thank you!

**Comment by deanwampler** [comment]
Thanks for offering to do a translation. We are making many changes now. A translation might be out of date quickly. I recommend waiting another month or two, when the first complete version is finished.

Does it make sense to the translated files under a `kr` or `korean` directory? Other translations could use their own directory. I can move the original files under `english`.

**Comment by marload** [comment]
Thanks!
