### ISSUE TITLE
Link broken on the README.md

### ISSUE THREAD

**Issue by lcipolina** [anyscale/academy#13]
Hi, these are all great resources. Thank you very much for putting this together. 

There is one link that might have been moved:
https://github.com/anyscale/academy/blob/master/rllib/00-Overview-Ray-RLlib.ipynb

The above link gives back 404-page not found

Here:
| A developer or data scientist interested in Reinforcement Learning | [_Ray RLlib_](rllib/00-Overview-Ray-RLlib.ipynb) |

**Comment by deanwampler** [comment]
Thanks for pointing this out! I found a few other similar errors and inconsistent naming of notebooks, which I've fixed on the `master` branch.
